name: Mergit

on:
  pull_request:
    types: [closed]

jobs:
  mergit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: odiseo159-beep/mergit@v1
        with:
          verifier-key: ${{ secrets.MERGIT_VERIFIER_KEY }}
